Testing manual approval and generating code steps.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -37,6 +37,18 @@ commands:
               echo "Nothing to do for forked PRs, so marking this step successful"
               circleci step halt
             fi
+  is_master_branch:
+    description: >-
+      Check to avoid certain steps/jobs being run from other branch than master.
+    steps:
+      - run:
+          name: Fail if not master branch
+          command: |
+            if [ -n "${CIRCLE_BRANCH}" = "master" ]; then
+              echo "Not master branch, aborting.."; exit 1;
+            else
+              echo "Proceeding from master..."
+            fi
 
 jobs:
   checkout_code:
@@ -87,10 +99,34 @@ jobs:
   test_browsers:
     <<: *defaults
     steps:
-      - early_return_for_forked_pull_requests
+      - early_return_for_forked_pull_requests # due to avoid secrets being passed on to forked PR builds we don't run browser tests initially
       - << : *restore_repo_cache
       - << : *restore_dependency_cache
       - run: npm run ci-test
+
+  build_dist:
+    <<: *defaults
+    steps:
+      - is_master_branch
+      # Checkout highcharts-declarations-generator
+      - add_ssh_keys:
+          fingerprints:
+            - "57:bb:46:ef:f4:22:f7:f3:67:5e:1f:2a:ad:7f:98:f6"
+      - run:
+          name: Avoid hosts unknown for github
+          command: echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
+      - run:
+          name: Clone Github highcharts-declarations-generator repository
+          command: git clone -b master --single-branch master --depth=1 /home/circleci/repo/highcharts-declarations-generator
+      - run:
+          name: Generate packages and docs
+          command: gulp dist
+      - store_artifacts:
+          path: /home/circleci/repo/highcharts/build
+      - run:
+          name: Install s3cmd
+          command: sudo apt-get install s3cmd
+      - run: echo -e "Upload via s3cmd not yet implemented."
 
 
 workflows:
@@ -123,3 +159,19 @@ workflows:
             branches:
               only:
                 - feature/circleci-integration
+      - hold_for_approval:
+          type: approval
+          requires:
+            - test_browsers
+          filters:
+            branches:
+              only:
+                - feature/circleci-integration
+      - build_dist:
+          requires:
+            - hold_for_approval
+          filters:
+            branches:
+              only:
+                - feature/circleci-integration
+
